# Generated by Django 5.2.4 on 2025-07-18 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_details',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_details',
            name='about_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person_details',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person_details',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
