# Generated by Django 5.2.4 on 2025-07-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0002_person_details_created_at_person_details_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_details',
            name='reg_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
