# Generated by Django 5.2.4 on 2025-07-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0003_person_details_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_details',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_details',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
