# Generated by Django 5.2.4 on 2025-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0004_person_details_slug_alter_person_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_details',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
