# Generated by Django 5.2.4 on 2025-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0006_person_details_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume_personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('linkedin', models.URLField(max_length=254, null=True)),
                ('github', models.URLField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person_details',
            name='phone_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
