# Generated by Django 5.2.4 on 2025-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0009_alter_resume_personal_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_personal_details',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
