# Generated by Django 5.2.4 on 2025-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0010_alter_resume_personal_details_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField()),
                ('degree', models.CharField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hsc_scl_name', models.CharField()),
                ('hsc_marks', models.IntegerField()),
                ('sslc_scl_name', models.CharField()),
                ('sslc_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person_details',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
