# Generated by Django 5.2.4 on 2025-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0011_resume_education_alter_person_details_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_personal_details',
            name='img_url',
            field=models.ImageField(null=True, upload_to='Resume/img/'),
        ),
    ]
