# Generated by Django 5.2.4 on 2025-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomers', '0012_resume_personal_details_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_education',
            name='college_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='resume_education',
            name='degree',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='resume_education',
            name='hsc_scl_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='resume_education',
            name='sslc_scl_name',
            field=models.CharField(max_length=254),
        ),
    ]
