"""
Django settings for Karthi project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import dj_database_url  
from pathlib import Path
import os
from decouple import config  # --> for environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # 'blog.onrender.com',  
    # 'boomers.onrender.com',
    
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'boomers',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware', # --> for static files in production
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Karthi.middleware.RegisteredUserMiddleware',
    'Karthi.middleware.RestrictUnregisterMiddleware',
]

ROOT_URLCONF = 'Karthi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  #--> For the error page we have to add the file.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Karthi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    
    'default': dj_database_url.parse(config('DATABASE_URL')),
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql', #postgresql
    #     # 'NAME': BASE_DIR / 'db.sqlite3',

    #     'NAME':  'postgres',  #--> DB Name
    #     'USER': 'postgres',
    #     'PASSWORD': 'Karthi39!',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
}

# DATABASES["default"] = dj_database_url.parse("postgresql://boomers_user:xb8zvX5TsVyJ1r0ySa6oAFVHgIZP4UC6@dpg-d248mmruibrs73acbpng-a.oregon-postgres.render.com/boomers")
# postgresql://boomers_user:xb8zvX5TsVyJ1r0ySa6oAFVHgIZP4UC6@dpg-d248mmruibrs73acbpng-a.oregon-postgres.render.com/boomers


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #--> for collectstatic command production

STATICFILES_DIRS = [
      BASE_DIR / 'blog/static/blog/',
      BASE_DIR / 'boomers/static/boomers/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# manually imported    -->  For logging setup
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",  # --> default:WARNING 
    },
}

# for email sending setup

DEFAULT_FROM_EMAIL = 'your_email@honest.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '1a852d62d3dcab'
EMAIL_HOST_PASSWORD = 'c90fbaf627262e'

# for image save from the form 
MEDIA_URL = '/media/'
MEDIA_ROOT =os.path.join(BASE_DIR,'media')


